### PR TITLE
React: consolidate cam, mic & transport state

### LINKED ISSUE #121: React: Changing micEnabled state does not work
Hi, I'm playing around with the react library and the library design looks great so far! I'm trying to use the `@pipecat-ai/client-react` library, but it seems that the state in the application is not correctly managed.

For example, we have the following custom component:

```js
import { useRTVIClientMicControl } from "@pipecat-ai/client-react";

export function MuteButton() {
  const { enableMic, isMicEnabled } = useRTVIClientMicControl();

  console.log("is mic enabled:", isMicEnabled);

  return (
    <button onClick={() => enableMic(!isMicEnabled)}>
      {isMicEnabled ? "Disable Microphone" : "Enable Microphone"}
    </button>
  );
}
```

I would assume that if I have two of these buttons and click on one of them, that the text of the other button also changes. However that is not the case:

Image

Also, the first click on a button usually enables the microphone, but a second click won't disable the microphone, even though the button text changes.
Interestingly, it will trigger "track started" events, though.

Do you have an idea how to solve these issues?

### PR DESCRIPTION
**Pull request by Regaddi**
Instead of maintaining cam, mic & transport state individually per instance these are now maintained in a surrounding `PipecatClientStateProvider` component and shared via React context.

Fixes #121.

### CODE REVIEW

File: client-react/src/PipecatClientState.tsx [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+import { usePipecatClient } from "./usePipecatClient";
+import { useRTVIClientEvent } from "./useRTVIClientEvent";
+
+export const PipecatClientCamStateContext = createContext<{
+  enableCam: (enabled: boolean) => void;
+  isCamEnabled: boolean;
+}>({
+  enableCam: () => {
+    throw new Error(
+      "RTVICamStateContext: enableCam() called outside of provider"
```
Comment (mattieruth) [inline client-react/src/PipecatClientState.tsx:19]:
```suggestion
      "PipecatClientCamStateContext: enableCam() called outside of provider"
```

File: client-react/src/PipecatClientState.tsx [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+  },
+  isCamEnabled: false,
+});
+export const PipecatClientMicStateContext = createContext<{
+  enableMic: (enabled: boolean) => void;
+  isMicEnabled: boolean;
+}>({
+  enableMic: () => {
+    throw new Error(
+      "RTVIMicStateContext: enableMic() called outside of provider"
```
Comment (mattieruth) [inline client-react/src/PipecatClientState.tsx:30]:
```suggestion
      "PipecatClientMicStateContext: enableMic() called outside of provider"
```

File: client-react/src/usePipecatClientCamControl.ts [hunk 3]
```diff
@@ -1,41 +1,14 @@
...
-    },
-    [client]
-  );
-
-  return {
-    enableCam,
-    isCamEnabled,
-  };
-};
+export const useRTVIClientCamControl = () =>
```
Comment (mattieruth) [inline client-react/src/usePipecatClientCamControl.ts:13]:
```suggestion
export const usePipecatClientCamControl = () =>
```

File: client-react/src/usePipecatClientMicControl.ts [hunk 4]
```diff
@@ -1,41 +1,15 @@
...
-
-  return {
-    enableMic,
-    isMicEnabled,
-  };
-};
+/**
+ * Hook to control microphone state
+ */
+export const useRTVIClientMicControl = () =>
```
Comment (mattieruth) [inline client-react/src/usePipecatClientMicControl.ts:14]:
```suggestion
export const usePipecatClientMicControl = () =>
```

File: client-react/src/usePipecatClientTransportState.ts [hunk 5]
```diff
@@ -4,17 +4,9 @@
...
-const transportStateAtom = atom<TransportState>("disconnected");
-
-export const usePipecatClientTransportState = () => {
-  const [transportState, setTransportState] = useAtom(transportStateAtom);
-
-  useRTVIClientEvent(RTVIEvent.TransportStateChanged, setTransportState);
-
-  return transportState;
-};
+export const useRTVIClientTransportState = () =>
```
Comment (mattieruth) [inline client-react/src/usePipecatClientTransportState.ts:11]:
```suggestion
export const usePipecatClientTransportState = () =>
```

**Review by mattieruth — APPROVED** [review]
i think this looks good. just naming updates needed

**Comment by Regaddi** [comment]
> just naming updates needed

I must have overlooked these when resolving the merge conflicts, thanks for catching!
